// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPG803FNVTfdKtKI0Zp5NAs1rcb2UmjX0',
    appId: '1:92316330429:web:5f5cb6038571ebb78dcad4',
    messagingSenderId: '92316330429',
    projectId: 'autosmith',
    authDomain: 'autosmith.firebaseapp.com',
    storageBucket: 'autosmith.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuiU--F--jNT6OLtHJKtfHySo-FrsMvmE',
    appId: '1:92316330429:android:c1137890e375b96f8dcad4',
    messagingSenderId: '92316330429',
    projectId: 'autosmith',
    storageBucket: 'autosmith.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfV08JQuFh9nRb4RDjqf9yGX2PPh-SjIs',
    appId: '1:92316330429:ios:805e41a3f70eda2b8dcad4',
    messagingSenderId: '92316330429',
    projectId: 'autosmith',
    storageBucket: 'autosmith.appspot.com',
    androidClientId: '92316330429-43taec558grji0b76n4ivkld7tamqvo0.apps.googleusercontent.com',
    iosClientId: '92316330429-7fq7kgera6u9u6n1ilk105heuncke8s5.apps.googleusercontent.com',
    iosBundleId: 'in.theananta.autosmith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfV08JQuFh9nRb4RDjqf9yGX2PPh-SjIs',
    appId: '1:92316330429:ios:fe0c8f7f96474a918dcad4',
    messagingSenderId: '92316330429',
    projectId: 'autosmith',
    storageBucket: 'autosmith.appspot.com',
    androidClientId: '92316330429-43taec558grji0b76n4ivkld7tamqvo0.apps.googleusercontent.com',
    iosClientId: '92316330429-a2ufp8rat7cf6gqb5kr02j8nopo91j3s.apps.googleusercontent.com',
    iosBundleId: 'in.theananta.autosmith.RunnerTests',
  );
}
